name: analysis
permissions: read-all
on: [ push, pull_request ]

env:
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}

jobs:
  forbiddenApis:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 20
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Forbidden Apis
        uses: ./.github/actions/run-gradle
        with:
          java: ${{ env.JAVA_VERSION }}
          arguments: forbiddenApis -DforbiddenApis
  pmd:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 20
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Pmd
        uses: ./.github/actions/run-gradle
        with:
          java: ${{ env.JAVA_VERSION }}
          arguments: pmdJavaPoet pmdMain pmdCodeGen pmdJmh -Dpmd
  spotbugs:
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: 20
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Spotbugs
        uses: ./.github/actions/run-gradle
        with:
          java: ${{ env.JAVA_VERSION }}
          arguments: spotbugsJavaPoet spotbugsMain spotbugsCodeGen spotbugsJmh -Dspotbugs
