name: Qodana
on: [ push, pull_request ]

env:
  GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
  GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
  JAVA_VERSION: 11

permissions:
  contents: read

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f
        with:
          disable-sudo: true
          egress-policy: audit
      - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Set up JDK ${{ env.JAVA_VERSION }}
        uses: Wandalen/wretry.action@e6cf3db7de3777ba5f999f903c2f4efdd9ac7288 # v1.0.36
        timeout-minutes: 5
        with:
          action: actions/setup-java@v3
          with: |
            distribution: temurin
            java-version: ${{ env.JAVA_VERSION }}
          attempt_limit: 3
          attempt_delay: 2000
      - name: Setup Gradle
        uses: Wandalen/wretry.action@e6cf3db7de3777ba5f999f903c2f4efdd9ac7288 # v1.0.36
        timeout-minutes: 5
        with:
          action: gradle/gradle-build-action@v2
          with: |
            cache-read-only: false
            arguments: help --no-scan
            generate-job-summary: false
          attempt_limit: 3
          attempt_delay: 2000
      - name: Build
        run: ./gradlew build -x test
      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@7afb26c0c2f325c0d5c21ea1f617c79c7f899337 # main
      - name: Upload SARIF file for GitHub Advanced Security Dashboard
        uses: github/codeql-action/upload-sarif@d186a2a36cc67bfa1b860e6170d37fb9634742c7 # v2.2.11
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
